### ISSUE TITLE
BUG (Front camera doesn't open/ rear does it instead)

### ISSUE THREAD

**Issue by Yoshimatsup** [arielhernandezmusa/capacitor-camera-preview#11]
![image](https://user-images.githubusercontent.com/27040028/67594662-3b357100-f73b-11e9-9656-092e82840a7c.png)

this condition is the main issue, in some devices, it works and then opens the front camera when I use CameraPreview.start({ position: 'front' }), but in another devices, for example my personal smartphone ( Xiaomi MI A2 Lite ), it doesn't, the rear camera is started instead.
I changed both results of this ternary if to Camera.CameraInfo.CAMERA_FACING_FRONT as a 'semi-workaround' and then opens the front camera in my phone, but the position argument on the .start function is useless, I'd appreciate some help.

Some fixes that would also be great:
1* After you take the picture, it gets a minimum zoom on the image display, since im doing a facial recognition thats a struggle
2* On most android/chrome devices, the picture you show on screen gets mirrorred, I use scaleX(-1) ot fix it, but could be a nice 'feature'

**Comment by Yoshimatsup** [comment]
I've been reading the code, looks like defaultCamera is set to "back" by a Fragment, but nothing listen the argument  to change to '"front" on the .start call

**Comment by arielhernandezmusa** [comment]
Ok, I'll see that problem

**Comment by arielhernandezmusa** [comment]
Can you please give me Android version?

**Comment by arielhernandezmusa** [comment]
@Yoshimatsup , I just fix the problem regarding to start with front or rear camera, the other issues, please separate in different issues and close this please.

**Comment by Yoshimatsup** [comment]
Thanks for your help, i'll separate the issues and close this one.
Thanks again!
