### ISSUE TITLE
iOS- Landscape not working properly.

### ISSUE THREAD

**Issue by mxdmedia** [arielhernandezmusa/capacitor-camera-preview#12]
I have created a very simple Ionic4/Angular app, that opens a full-screen camera preview (I am not even worrying about image capture at this point).  If the device is in portrait orientation when the camera is opened, everything looks great.  If, however, the phone is then rotated to a portrait position, the preview shrinks to the left half of the screen, and the image is rotated 90 degrees from what it should be.

Additionally, if the device is already in a landscape orientation when the preview is opened, the preview fills the entire screen, but is rotated 90 degrees.  Re-orienting the phone to a portrait orientation, shows the preview rotated correctly, but it now only fills the top half of the screen.  I have posted my simple `camera.page.ts` file below.  Are there some undocumented settings I am missing for orientation?  (My intent is to have a camera page/component, where the user can take multiple pictures which will be grouped together by my app.  The user must be able to take pictures in both portrait and landscape orientations)

```ts
import { Component, OnInit } from '@angular/core';
import 'capacitor-camera-preview';

import { Plugins } from '@capacitor/core';

const { CameraPreview } = Plugins;

@Component({
  selector: 'app-camera',
  templateUrl: './camera.page.html',
  styleUrls: ['./camera.page.scss']
})
export class CameraPage implements OnInit {
  constructor() {}

  ngOnInit() {
    CameraPreview.start({ position: 'rear' });
  }
}
```

**Comment by arielhernandezmusa** [comment]
Hi, sorry by my late answer, I’ll fix this as soon as possible, if you can help me will be great, thanks.
