### ISSUE TITLE
Flipped image on Android

### ISSUE THREAD

**Issue by abhibly** [arielhernandezmusa/capacitor-camera-preview#15]
Hello,
I am using your plugin in the Ionic4-android app. When I capture the picture, the base64 data is returned and when I display it, the image is rotated.
This issue is occurring when the camera position is front on the Android device. When tested with position:'rear' it works fine.

This is the version I am using:
`"capacitor-camera-preview": "^0.2.0"`

I am attaching the screenshots of issue:
`Before capturing the picture:`
![Screenshot_2020-02-08-12-49-47-341_com transistorsoft backgroundgeolocation ionic2](https://user-images.githubusercontent.com/15784815/74081172-f5927f00-4a71-11ea-811f-5a570379df8a.png)
`Displaying base64 data:`
![Screenshot_2020-02-08-12-50-31-437_com transistorsoft backgroundgeolocation ionic2](https://user-images.githubusercontent.com/15784815/74081174-f75c4280-4a71-11ea-90da-e75bd8aa97dc.png)

Can somebody tell me how to fix this issue?

**Comment by benbut** [comment]
I have the same problem

**Comment by NauelG** [comment]
Do you solve de issue?
