### ISSUE TITLE
Extra options

### ISSUE THREAD

**Issue by nielsvanharen** [arielhernandezmusa/capacitor-camera-preview#17]
Hello,  great copy from the cordova plugin, we are using it in our migrated capacitor app atm. My only concern for now is the lack of default options. It would be great to offer more options available like the original plugin. It would be a great help to have at least the height and weight properties, but the same would be even better :)

**Comment by arielhernandezmusa** [comment]
yeah, I will try to copy all features :-), but if you can help me, I'll feel  better

**Comment by bialabs** [comment]
any advices on how to crop and resize the image from your plugin?

**Comment by nielsvanharen** [comment]
> in the meantime you add all the extra options, any advices on how to crop and resize the image from your plugin?

   CameraPreview.capture(pictureOpts).then((base64PictureData) => {
                    // We pass width, height, x and y coordinates of our rectangle to crop func
                    // BEFORE crop function ends, it sends cropped base64 image to a server
                    this.crop(base64PictureData.value, rectWidth, rectHeight, xCoord, yCoord, (croppedBase64Image) => {
 //do stuff with your image
})

   crop(base64PictureData, rectWidth, rectHeight, xCoord, yCoord, callback: (param) => void) {

        // image will contain ORIGINAL image
        const image = new window.Image();

        // image will contain CROPPED image
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');

        // Load original image into image element
        image.src = 'data:image/png;base64,' + base64PictureData;
        image.onload = () => {

            const scaleHeight = rectHeight / image.height;
            const scaleWidth = rectWidth / image.width;

            let scale;
            let xImgUnits;
            let yImgUnits;
            if (scaleHeight < scaleWidth) {
                scale = scaleWidth;
                xImgUnits = 0;
                yImgUnits = (image.height - (rectHeight / scale)) / 2;
            } else {
                scale = scaleHeight;
                xImgUnits = (image.width - (rectWidth / scale)) / 2;
                yImgUnits = 0;
            }

            const rectWidthImgUnits = rectWidth / scale;
            const rectHeightImageUnits = rectHeight / scale;

            // Set canvas size equivalent to interpolated rectangle size
            canvas.width = rectWidthImgUnits;
            canvas.height = rectHeightImageUnits;

            ctx.drawImage(image,
                xImgUnits, yImgUnits,                       // Start CROPPING from (x_img_units, y_img_units).
                rectWidthImgUnits, rectHeightImageUnits,    // Crop interpolated rectangle
                0, 0,                                           // Place the result at 0, 0 in the canvas,
                rectWidthImgUnits, rectHeightImageUnits);   // Crop interpolated rectangle

            // Get base64 representation of cropped image
            const croppedBase64Image = canvas.toDataURL();

            // Now we are ready to send cropped image TO SERVER
            callback(croppedBase64Image);


            return croppedBase64Image;
        };
    }

this draws a box to take the picture from (license plate for example)

**Comment by nielsvanharen** [comment]
the markup is terrible, stupid code plugin

**Comment by nielsvanharen** [comment]
> yeah, I will try to copy all features :-), but if you can help me, I'll feel better

hey can you add me as a contributor? Ik have made some changes for the ios implementation on orientation. I can make a pr if you want, thanks

**Comment by arielhernandezmusa** [comment]
I just added you
