### ISSUE TITLE
CameraPreview stop camera completely

### ISSUE THREAD

**Issue by arochet** [arielhernandezmusa/capacitor-camera-preview#19]
Hi,
Thank you for the plug-in. It works for me but i got a problem when i use CameraPreview.stop() : 
The video disappear well but the camera is still turn on. I can see on my Mac the green light of the camera and on Chrome the round that indicate the camera doesn't turn off. Then, when i use the basic Camera plug-in, my app crash on Android. 

Thank you very much for your help.

**Comment by arielhernandezmusa** [comment]
@arochet, I fix the problem when stopping the camera con web in this commit:

https://github.com/arielhernandezmusa/capacitor-camera-preview/commit/3fb8f65ee90472707f87f9c4d7540a01ef5f2135

for the android issues, please provide more details.

Thanks
