### ISSUE TITLE
How to save preview image to object?

### ISSUE THREAD

**Issue by suenot** [arielhernandezmusa/capacitor-camera-preview#22]
I want to save preview image to object, that send as props for child component.

**Comment by nielsvanharen** [comment]
im not entirely sure what you mean. You want to convert de base64 string to a blob ?

**Comment by suenot** [comment]
I am closing this issue. I think that send changing data for child component is a bad idea, because it can cause many rerenders of child component.

Thanks for quick response. It's important feature for open source projects. 👍
