### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by arochet** [arielhernandezmusa/capacitor-camera-preview#29]
Hi,

I followed the instructions on the Documentation. On android, the plugin works but I have a blank page. The background color is not transparent. 

Here the solution I found on Internet : 
`ion-content { --background: transparent !important; }`
Add this code in css file of the component.

Maybe it could be good to add this in the documentation ?

**Comment by arielhernandezmusa** [comment]
Please read this issue and let me know if solve the problem

**Comment by arielhernandezmusa** [comment]
https://github.com/arielhernandezmusa/capacitor-camera-preview/issues/20

**Comment by arielhernandezmusa** [comment]
Yeah, the documentation is not good :-(, I'll try to improve it, thanks.
