### ISSUE TITLE
Plugin does not work on iPhone 6S Plus. No camera available error occurred

### ISSUE THREAD

**Issue by ryaa** [arielhernandezmusa/capacitor-camera-preview#3]
The problems seems to be in the below line
`let session = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInDualCamera], mediaType: AVMediaType.video, position: .unspecified)`

builtInDualCamera type seems to be support on newer iPhones (iPhone 7 and above). Changing the above line to
`let session = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInWideAngleCamera], mediaType: AVMediaType.video, position: .unspecified)`
seems fixes the problem

I created a pull require with this change plus some other minor enhancements (reject/return error details etc.) - see https://github.com/arielhernandezmusa/capacitor-camera-preview/pull/4

**Comment by arielhernandezmusa** [comment]
Close this issue, pull request merged, thanks.
