### ISSUE TITLE
Is Android support ready to use?

### ISSUE THREAD

**Issue by jesobreira** [arielhernandezmusa/capacitor-camera-preview#5]
I see that commit #29ebeb5 aims to have added Android support.

However on my tests, it only works on iOS. Under Android, the plugin is not available under @capacitor/core/Plugins namespace.

```
import { Plugins } from "@capacitor/core"
const { CameraPreview } = Plugins

console.log(CameraPreview, Plugins)
CameraPreview.start()
```
![Screen Shot 2019-08-30 at 12 15 06](https://user-images.githubusercontent.com/3002249/64031959-e224d480-cb1f-11e9-9f8c-df13e2acf153.png)

Am I missing something? Or Android support is still under development?

Thank you!

**Comment by arielhernandezmusa** [comment]
Did you add the plugin to MainActivity?

**Comment by jesobreira** [comment]
Thank you for your response!

What should be added to MainActivity?

**Comment by arielhernandezmusa** [comment]
You need to add 

add(CameraPreview.class);

To the init method

**Comment by jesobreira** [comment]
Thank you!

Is this disclosed on the README or some plugin-specified docs? If not, may I send a PR?

Going a little out of the issue subject, is there support for switching the front/rear camera?

**Comment by arielhernandezmusa** [comment]
In the capacitor’s documentation is explained how to used the plugins, but I believe that I have to include it on documentation.

Switching camera is not supported right now, a PR is welcome ;-)
