### ISSUE TITLE
Ios

### ISSUE THREAD

**Issue by elepetit** [arielhernandezmusa/capacitor-camera-preview#7]
Hello,

On Ios, the plugin starts well but unable to view the camera.
My css include a background transparent.

Thx for your work !

**Comment by arielhernandezmusa** [comment]
Hi, can you provide more details, such as iOS version, device ...

**Comment by elepetit** [comment]
Hey,

That's ok now. I've to put

` ion-content { --background: transparent !important; }`

in my scss page for Ionic4
but It seems that front doesn't work.
I've got only the rear camera.

**Comment by arielhernandezmusa** [comment]
Did you try flip() it?

**Comment by elepetit** [comment]
Iphone 7
Ios 12.4.1
Ionic4

**Comment by arielhernandezmusa** [comment]
OH, unfortunately, I don't have an iPhone with ios 12.4.1, I just test it on iPhone 7 plus ios 13 and its work

**Comment by arielhernandezmusa** [comment]
If you find the problem please, create a pull request with a fix

**Comment by elepetit** [comment]
tried to flip, CameraPreview.flip(); but nothing works

**Comment by elepetit** [comment]
the swift code looks good.. hum hum ! where's the pb on ios 12....

**Comment by elepetit** [comment]
Hi,

I've found the problem.
You were not handling the position option.
I've modified Plugin.swift and CamaraController.swift and that's ok

**Comment by elepetit** [comment]
unfortunately ompossible to create a pull

**Comment by arielhernandezmusa** [comment]
Ok, can you send ti me the changes you made?

**Comment by elepetit** [comment]
in Plugin.swift

`@objc func start(_ call: CAPPluginCall) {
**//add getter for position**
        guard let camera_option = call.options["position"] as? String else{
            call.reject("Must provide position")
            return
        }
        DispatchQueue.main.async {
            if (self.cameraController.captureSession?.isRunning ?? false) {
                call.reject("camera already started")
            } else {
**//send camera_option as camera_position**
                self.cameraController.prepare(camera_position: camera_option){error in
                    if let error = error {
                        print(error)
                        call.reject(error.localizedDescription)
                        return
                    }
                    self.previewView = UIView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.size.width, height: UIScreen.main.bounds.size.height))
                    self.webView.isOpaque = false
                    self.webView.backgroundColor = UIColor.clear
                    self.webView.superview?.addSubview(self.previewView)
                    self.webView.superview?.bringSubviewToFront(self.webView)
                    try? self.cameraController.displayPreview(on: self.previewView)
                    call.resolve()

                }
            }
        }
    }`

**Comment by elepetit** [comment]
in CameraController

`func configureDeviceInputs() throws {
            guard let captureSession = self.captureSession else { throw CameraControllerError.captureSessionIsMissing }
            
            **if camera_position == "rear"**{
                if let rearCamera = self.rearCamera {
                    self.rearCameraInput = try AVCaptureDeviceInput(device: rearCamera)
                    
                    if captureSession.canAddInput(self.rearCameraInput!) { captureSession.addInput(self.rearCameraInput!) }
                    
                    self.currentCameraPosition = .rear
                }
            }
            **else if camera_position == "front"**{
                if let frontCamera = self.frontCamera {
                    self.frontCameraInput = try AVCaptureDeviceInput(device: frontCamera)
                    
                    if captureSession.canAddInput(self.frontCameraInput!) { captureSession.addInput(self.frontCameraInput!) }
                    else { throw CameraControllerError.inputsAreInvalid }
                    
                    self.currentCameraPosition = .front
                }
            }
            else { throw CameraControllerError.noCamerasAvailable }
        }`

**Comment by arielhernandezmusa** [comment]
Perfect, thank, I'll apply these changes soon.

**Comment by elepetit** [comment]
Ok
I’m working on options

**Comment by BrunoTCouto** [comment]
Hi ! I'm having the same issue ! any prediction when this chnges will be merged ?

**Comment by arielhernandezmusa** [comment]
Hi, I was on vacations so maybe tomorrow I fix it

**Comment by BrunoTCouto** [comment]
Great ! thanks for the update !

**Comment by arielhernandezmusa** [comment]
@BrunoTCouto , @elepetit the fix is done :-) thanks @elepetit for your help

**Comment by BrunoTCouto** [comment]
@arielhernandezmusa Thanks ! Going to test the fix!

**Comment by BrunoTCouto** [comment]
Hm, looks like my issue is not exactly related with this one. Will be opening an new issue with more details
