### ISSUE TITLE
[iOS] - camera already started

### ISSUE THREAD

**Issue by BrunoTCouto** [arielhernandezmusa/capacitor-camera-preview#8]
Hi,
I'm trying to open the camera in my iPhone but i'm receiving the following error "camera already started", but its the first time the camera is starting...
Not sure what is causing this issue... 

iPhone x Max
iOS  13.1

by the way, the plugin is working fine in the browser :)
thanks for the great plugin !

**Comment by BrunoTCouto** [comment]
And the project is runing in Vue with Typescript

**Comment by BrunoTCouto** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/23619646/66437792-1f269580-ea01-11e9-9dbe-41ebe757f5f8.png">

**Comment by BrunoTCouto** [comment]
![IMG_2583](https://user-images.githubusercontent.com/23619646/66437848-48dfbc80-ea01-11e9-949c-c97ef6882a96.PNG)

**Comment by elepetit** [comment]
Hi Bruno

Can you provide full code of opening the camera?

**Comment by BrunoTCouto** [comment]
```ts
import { Component, Prop, Vue } from 'vue-property-decorator';
import { MediaCameraValidation } from './media-camera-validation.interface';
import 'capacitor-camera-preview'
import { Plugins } from '@capacitor/core'

const { CameraPreview } = Plugins
 
@Component({})
export class MediaCameraComponent extends Vue {

    @Prop({ default: 'enviroment', type: String })
    public facingMode: string;

    @Prop({ default: 20, type: Number })
    public preferredMaskPaddingTop: number;

    @Prop({ default: 300, type: Number })
    public preferredMaskWidth: number;

    @Prop({ default: 345, type: Number })
    public preferredMaskHeight: number;

    @Prop({ default: [], type: Array })
    public validations: MediaCameraValidation[];

    @Prop({ default: false, type: Boolean })
    public faceValidation: boolean;
    
    public containerHeight: number = window.screen.height;
    public containerWidth: number = window.screen.width;
    public containerZoom: number = 100;
    public maskWidth: number = 0;
    public maskHeight: number = 0;
    public maskPaddingTop: number = 0;

    public loading: boolean = false;
    public captured: boolean = false;
    public rejectedCamera: boolean = false;
    public container: HTMLDivElement = undefined;
    public canvas: HTMLCanvasElement = undefined;
    public mediaStreamTrack: MediaStreamTrack;

    public constraints: MediaStreamConstraints = null;
    
    public async mounted() {
        this.container = this.$refs['media-camera-container'] as HTMLDivElement;
        this.canvas = this.$refs['media-camera-canvas'] as HTMLCanvasElement;
        CameraPreview.start({position: 'rear', parent: 'cameraPreview', className: 'cameraPreview'});
    }

    public async capturePicture() {
    }

    private async drawPictureOnCanvas(picture: string): Promise<void> {
        return new Promise((resolve,reject) => {
            try {
                let image = new Image();
                
                image.onload = async () => {
                    this.canvas.width = document.getElementsByClassName('camera-cordova')[0].clientWidth >= 480 ?  document.getElementsByClassName('camera-cordova')[0].clientWidth : 480;
                    this.canvas.height = document.getElementsByClassName('camera-cordova')[0].clientHeight >= 640 ? document.getElementsByClassName('camera-cordova')[0].clientHeight : 640;
                    var context = this.canvas.getContext('2d');
                    context.drawImage(image, 0, 0, this.canvas.width, this.canvas.height);
                    resolve();
                };
                image.src = `data:image/png;base64,${picture}`;
            } catch (error) {
                reject(error);
            }
        })
    }

    private async validatePicture() {
        setImmediate(async () => {
            const validations = [...this.validations];
            const errors: string[] = [];
            while (validations.length) {
                const validation = validations.shift();
                await validation(this.canvas, this.maskWidth, this.maskHeight).catch(error => errors.push(error));
            }

            this.unsetCameraMode();
            if (errors.length) {
                this.cancelPicture();
                this.$emit('on-capture-fail', errors);
            } else {
                this.captured = true;
            }

            this.loading = false;
        });
    }

    public cancelPicture() {
        // this.cameraPreview.stopCamera();
        // this.initializeCamera();
        // this.clearCanvasImage();
    }

    public confirmPicture() {
        // this.cameraPreview.stopCamera();
        // this.$emit('on-capture-confirm', this.canvas.toDataURL());
    }

    public onCloseModal() {
        this.rejectedCamera = false;
        // this.initializeCamera();
    }

    private getCameraPreviewOpts() {
        let cameraPreviewOpts = {
            x: 0,
            y: 0,
            width: this.containerWidth,
            height: this.containerHeight,
            camera: this.facingMode == ('user') ? 'front' : 'back',
            toBack: true,
        };
        return cameraPreviewOpts;
    }

    private setCameraMode() {
        if (this.facingMode == 'user') {
            // FIX ME CORDOVA
            // if (device.platform === 'Android') {
            //     this.cameraPreview.setZoom(this.containerZoom);
            // }
        }
        let html = document.getElementsByTagName('html')[0];
        html.className += 'camera-cordova';
    }

    private unsetCameraMode() {
        let html = document.getElementsByTagName('html')[0];
        html.className = '';
    }

    private clearCanvasImage() {
        setTimeout(() => { //Workaround para não mostrar o cinza de fundo
            let context = this.canvas.getContext('2d');
            context.scale(-1, 1);
            context.clearRect(0, 0, this.canvas.width, this.canvas.height);
            context.clearRect(this.canvas.width * -1, 0, this.canvas.width, this.canvas.height);
        }, 1000);
    }
}
```

**Comment by BrunoTCouto** [comment]
There is lots of unused code, we are migrating from cordova to capacitor

But the error ocurs in the mounted section

**Comment by arielhernandezmusa** [comment]
I'm not an expert on Vue, but is `mounted` called only once?

**Comment by BrunoTCouto** [comment]
Yes

**Comment by elepetit** [comment]
can you skip parent and class in the start command ?

**Comment by elepetit** [comment]
CameraPreview.start({position:rear})

**Comment by elepetit** [comment]
I think you should not import Capacitor-Camera-Preview line 3

**Comment by elepetit** [comment]
import {
  Plugins,
  Capacitor
} from "@capacitor/core";
const { CameraPreview} = Plugins;

**Comment by BrunoTCouto** [comment]
Im going test skiping the parent and the class.

if i don't import Capacitor-Camera-Preview in line 3 the camera doesn't open in the browser as well

**Comment by elepetit** [comment]
What about import with Plugins and Capacitor, like


import {
Plugins,
Capacitor,
Camera-preview
} from "@capacitor/core";

**Comment by elepetit** [comment]
not expert in vue but seems like your import already starts the camera preview, and when you call mounted it makes twice

**Comment by elepetit** [comment]
I’m on holidays, will try to help you next week

**Comment by BrunoTCouto** [comment]
Ok ! I'm already testing this options

Any update i will write here !

Thanks!

**Comment by BrunoTCouto** [comment]
Without importing i get the following error:

Browser:
uncaught exception: CameraPreview does not have web implementation.

iOS:
{message: "camera already started", errorMessage: ""}

**Comment by BrunoTCouto** [comment]
Just printed the condition that rejects in swift and ```self.cameraController.captureSession?.isRunning``` is ```nil``` so it should not enter in the if clause right ?

```swift 
if(self.cameraController.captureSession?.isRunning ?? false) {
    call.reject("camera already started")
}
```

**Comment by elepetit** [comment]
yes

**Comment by BrunoTCouto** [comment]
Looks like the error "camera already started" was my fault... For getting the error log i was refreshing the webview in safari...
Now the camera is starting correctly but not displaying in the screen

**Comment by BrunoTCouto** [comment]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/23619646/66441562-da552b80-ea0d-11e9-8e8e-c1171afcefaf.png">

**Comment by elepetit** [comment]
you should consider your css

**Comment by BrunoTCouto** [comment]
In ios, where is expected the code put the "video"element ?

**Comment by elepetit** [comment]
in your page’s scss
ion-content { --background: transparent !important; }

**Comment by elepetit** [comment]
your preview is in the back

**Comment by arielhernandezmusa** [comment]
As @elepetit says, the preview on android and ios is on a view back of root view, so to view the camera preview you have to make the  background transparent !!!

**Comment by BrunoTCouto** [comment]
Fixed ! As I migrated the project from cordova to Ionic I forgot to add the ```<ion-app/>```and ```<ion-content/>``` tags. After this everything started working! 
Thanks !! :)
![img_2586](https://user-images.githubusercontent.com/23619646/66449498-a8eb5880-ea2b-11e9-8ff9-1f709a612668.png)

**Comment by elepetit** [comment]
you’re welcome!

**Comment by ryaa** [comment]
> not expert in vue but seems like your import already starts the camera preview, and when you call mounted it makes twice

@elepetit My app also has 'camera already started' error happening intermittently. Some users experience this error periodically and this is logged into our system however I can not reproduce this problem on my iOS devices.
I have the below import in **app.module.ts** and wondering if it might cause any problems? (note that i use capacitor 5 and the latest version of this plugin 5.0.0)
`import '@capacitor-community/camera-preview';`
Specifically, why do you think that it can make the camera to start twice?

I noticed that this was required to support the plugin on the web platform for the capacitor 3 (see https://github.com/capacitor-community/camera-preview/tree/capacitor-3-support#web-quirks) however this seems no longer required for the capacitor 5 (see https://github.com/capacitor-community/camera-preview#extra-web-installation-steps)
